spring:
    application:
        name: book-store-management
    datasource:
        url: jdbc:mysql://localhost:3306/book_store
        password: root
        username: root
    liquibase:
        change-log: classpath*:db/change-log.xml
